# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LabelClear.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelClear(object):
    def setupUi(self, LabelClear):
        LabelClear.setObjectName("LabelClear")
        LabelClear.resize(200, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LabelClear.sizePolicy().hasHeightForWidth())
        LabelClear.setSizePolicy(sizePolicy)
        LabelClear.setMinimumSize(QtCore.QSize(200, 200))
        LabelClear.setMaximumSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(LabelClear)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 12pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setMinimumSize(QtCore.QSize(100, 0))
        self.btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn.setStyleSheet("font: 12pt \"Arial\";")
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        LabelClear.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LabelClear)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        LabelClear.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LabelClear)
        self.statusbar.setObjectName("statusbar")
        LabelClear.setStatusBar(self.statusbar)

        self.retranslateUi(LabelClear)
        self.btn.clicked.connect(self.label.clear)
        QtCore.QMetaObject.connectSlotsByName(LabelClear)

    def retranslateUi(self, LabelClear):
        _translate = QtCore.QCoreApplication.translate
        LabelClear.setWindowTitle(_translate("LabelClear", "Label Clearer"))
        self.label.setText(_translate("LabelClear", "Clear me!"))
        self.btn.setText(_translate("LabelClear", "Push Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabelClear = QtWidgets.QMainWindow()
    ui = Ui_LabelClear()
    ui.setupUi(LabelClear)
    LabelClear.show()
    sys.exit(app.exec_())
