# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 698)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTreeView, QListView\n"
"{\n"
"    background-color: silver;\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 1px solid darkgray;*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/dark_orange/img/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 1px solid darkgray;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/dark_orange/img/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/dark_orange/img/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 8px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #3A3939;\n"
"    width: 8px;\n"
"    background: #201F1F;\n"
"    margin: 0 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
"      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: 0 -4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid darkgray;\n"
"\n"
"    border-radius: 2px;\n"
"    min-width: 50px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_refresh.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_refresh.setStyleSheet("font: 75 16pt \"Century Gothic\";")
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_2.addWidget(self.btn_refresh)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(48, 48))
        self.logo.setMaximumSize(QtCore.QSize(48, 48))
        self.logo.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/png/gfx/Wrench_font_awesome_original.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.app_label = QtWidgets.QLabel(self.centralwidget)
        self.app_label.setStyleSheet("font: 75 30pt \"Century Gothic\";\n"
"color: rgb(223, 223, 223);\n"
"background-color: rgb(115, 115, 115);\n"
"\n"
"")
        self.app_label.setAlignment(QtCore.Qt.AlignCenter)
        self.app_label.setObjectName("app_label")
        self.horizontalLayout_3.addWidget(self.app_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setStyleSheet("font: 75 16pt \"Century Gothic\";")
        self.tabs.setObjectName("tabs")
        self.tab_inv_dets = QtWidgets.QWidget()
        self.tab_inv_dets.setObjectName("tab_inv_dets")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_inv_dets)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.tab_inv_dets)
        self.label_14.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.count_num = QtWidgets.QSpinBox(self.tab_inv_dets)
        self.count_num.setMinimumSize(QtCore.QSize(52, 0))
        self.count_num.setMaximumSize(QtCore.QSize(80, 16777215))
        self.count_num.setObjectName("count_num")
        self.horizontalLayout.addWidget(self.count_num)
        self.btn_search = QtWidgets.QPushButton(self.tab_inv_dets)
        self.btn_search.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_search.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.table_inv = QtWidgets.QTableWidget(self.tab_inv_dets)
        self.table_inv.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.table_inv.setObjectName("table_inv")
        self.table_inv.setColumnCount(9)
        self.table_inv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.table_inv.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.table_inv)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_inv_dets, "")
        self.inv_stats_tab = QtWidgets.QWidget()
        self.inv_stats_tab.setObjectName("inv_stats_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.inv_stats_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.inv_stats_tab)
        self.label.setMinimumSize(QtCore.QSize(260, 0))
        self.label.setMaximumSize(QtCore.QSize(260, 16777215))
        self.label.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 5, 1, 1)
        self.num_ref = QtWidgets.QLabel(self.inv_stats_tab)
        self.num_ref.setMinimumSize(QtCore.QSize(80, 0))
        self.num_ref.setMaximumSize(QtCore.QSize(80, 16777215))
        self.num_ref.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.num_ref.setObjectName("num_ref")
        self.gridLayout_6.addWidget(self.num_ref, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.inv_stats_tab)
        self.label_5.setMinimumSize(QtCore.QSize(260, 0))
        self.label_5.setMaximumSize(QtCore.QSize(260, 16777215))
        self.label_5.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 2, 1, 1)
        self.min_num_holes_ref = QtWidgets.QLabel(self.inv_stats_tab)
        self.min_num_holes_ref.setMinimumSize(QtCore.QSize(80, 0))
        self.min_num_holes_ref.setMaximumSize(QtCore.QSize(80, 16777215))
        self.min_num_holes_ref.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.min_num_holes_ref.setObjectName("min_num_holes_ref")
        self.gridLayout_6.addWidget(self.min_num_holes_ref, 0, 4, 1, 1)
        self.min_num_holes = QtWidgets.QLabel(self.inv_stats_tab)
        self.min_num_holes.setMinimumSize(QtCore.QSize(80, 0))
        self.min_num_holes.setMaximumSize(QtCore.QSize(80, 16777215))
        self.min_num_holes.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.min_num_holes.setObjectName("min_num_holes")
        self.gridLayout_6.addWidget(self.min_num_holes, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.inv_stats_tab)
        self.label_3.setMinimumSize(QtCore.QSize(260, 0))
        self.label_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.label_3.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 0, 1, 1)
        self.num_parts = QtWidgets.QLabel(self.inv_stats_tab)
        self.num_parts.setMinimumSize(QtCore.QSize(80, 0))
        self.num_parts.setMaximumSize(QtCore.QSize(80, 16777215))
        self.num_parts.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.num_parts.setObjectName("num_parts")
        self.gridLayout_6.addWidget(self.num_parts, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.inv_stats_tab)
        self.label_7.setMinimumSize(QtCore.QSize(260, 0))
        self.label_7.setMaximumSize(QtCore.QSize(260, 16777215))
        self.label_7.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 2, 1, 1)
        self.max_num_holes = QtWidgets.QLabel(self.inv_stats_tab)
        self.max_num_holes.setMinimumSize(QtCore.QSize(80, 0))
        self.max_num_holes.setMaximumSize(QtCore.QSize(80, 16777215))
        self.max_num_holes.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.max_num_holes.setObjectName("max_num_holes")
        self.gridLayout_6.addWidget(self.max_num_holes, 1, 3, 1, 1)
        self.max_num_holes_ref = QtWidgets.QLabel(self.inv_stats_tab)
        self.max_num_holes_ref.setMinimumSize(QtCore.QSize(80, 0))
        self.max_num_holes_ref.setMaximumSize(QtCore.QSize(80, 16777215))
        self.max_num_holes_ref.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.max_num_holes_ref.setObjectName("max_num_holes_ref")
        self.gridLayout_6.addWidget(self.max_num_holes_ref, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.label_15 = QtWidgets.QLabel(self.inv_stats_tab)
        self.label_15.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_top_3 = QtWidgets.QTableWidget(self.inv_stats_tab)
        self.table_top_3.setMinimumSize(QtCore.QSize(600, 200))
        self.table_top_3.setMaximumSize(QtCore.QSize(600, 200))
        self.table_top_3.setStyleSheet("font: 10pt \"Century Gothic\";")
        self.table_top_3.setObjectName("table_top_3")
        self.table_top_3.setColumnCount(3)
        self.table_top_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_top_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_top_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_top_3.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.table_top_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_check = QtWidgets.QPushButton(self.inv_stats_tab)
        self.btn_check.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_check.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_check.setObjectName("btn_check")
        self.verticalLayout_4.addWidget(self.btn_check)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 1, 0, 1, 1)
        self.tabs.addTab(self.inv_stats_tab, "")
        self.tab_edit_inv = QtWidgets.QWidget()
        self.tab_edit_inv.setObjectName("tab_edit_inv")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_edit_inv)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_first = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_first.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_first.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_first.setStyleSheet("")
        self.btn_first.setObjectName("btn_first")
        self.horizontalLayout_6.addWidget(self.btn_first)
        self.btn_prev = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_prev.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_prev.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_prev.setStyleSheet("")
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout_6.addWidget(self.btn_prev)
        self.btn_next = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_next.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_next.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_next.setStyleSheet("")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_6.addWidget(self.btn_next)
        self.btn_last = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_last.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_last.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_last.setStyleSheet("")
        self.btn_last.setObjectName("btn_last")
        self.horizontalLayout_6.addWidget(self.btn_last)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)
        self.btn_update = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_update.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_update.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_6.addWidget(self.btn_update)
        self.btn_del = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_del.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_del.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout_6.addWidget(self.btn_del)
        self.btn_add = QtWidgets.QPushButton(self.tab_edit_inv)
        self.btn_add.setMinimumSize(QtCore.QSize(52, 0))
        self.btn_add.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_6.addWidget(self.btn_add)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem15, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.edit_part_name = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_part_name.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_part_name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_part_name.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_part_name.setObjectName("edit_part_name")
        self.gridLayout_5.addWidget(self.edit_part_name, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 7, 3, 1, 1)
        self.edit_ref = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_ref.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_ref.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_ref.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_ref.setText("")
        self.edit_ref.setObjectName("edit_ref")
        self.gridLayout_5.addWidget(self.edit_ref, 4, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem16, 3, 0, 1, 1)
        self.edit_min_dia = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_min_dia.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_min_dia.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_min_dia.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_min_dia.setObjectName("edit_min_dia")
        self.gridLayout_5.addWidget(self.edit_min_dia, 5, 4, 1, 1)
        self.edit_min_area = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_min_area.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_min_area.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_min_area.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_min_area.setObjectName("edit_min_area")
        self.gridLayout_5.addWidget(self.edit_min_area, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_13.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_11.setMinimumSize(QtCore.QSize(200, 0))
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_11.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 6, 3, 1, 1)
        self.edit_max_area = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_max_area.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_max_area.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_max_area.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_max_area.setObjectName("edit_max_area")
        self.gridLayout_5.addWidget(self.edit_max_area, 7, 1, 1, 1)
        self.edit_max_dia = QtWidgets.QLineEdit(self.tab_edit_inv)
        self.edit_max_dia.setMinimumSize(QtCore.QSize(200, 0))
        self.edit_max_dia.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_max_dia.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_max_dia.setObjectName("edit_max_dia")
        self.gridLayout_5.addWidget(self.edit_max_dia, 6, 4, 1, 1)
        self.edit_count = QtWidgets.QSpinBox(self.tab_edit_inv)
        self.edit_count.setMinimumSize(QtCore.QSize(52, 0))
        self.edit_count.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_count.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_count.setMaximum(999)
        self.edit_count.setObjectName("edit_count")
        self.gridLayout_5.addWidget(self.edit_count, 7, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_10.setMinimumSize(QtCore.QSize(200, 0))
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_10.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_9.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 3, 1, 1)
        self.edit_num_holes = QtWidgets.QSpinBox(self.tab_edit_inv)
        self.edit_num_holes.setMinimumSize(QtCore.QSize(52, 0))
        self.edit_num_holes.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_num_holes.setStyleSheet("font: 12pt \"Century Gothic\";")
        self.edit_num_holes.setMaximum(999)
        self.edit_num_holes.setObjectName("edit_num_holes")
        self.gridLayout_5.addWidget(self.edit_num_holes, 4, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 7, 0, 1, 1)
        self.edit_id = QtWidgets.QLabel(self.tab_edit_inv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_id.sizePolicy().hasHeightForWidth())
        self.edit_id.setSizePolicy(sizePolicy)
        self.edit_id.setMinimumSize(QtCore.QSize(200, 30))
        self.edit_id.setMaximumSize(QtCore.QSize(200, 30))
        self.edit_id.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(172, 172, 172);\n"
"")
        self.edit_id.setText("")
        self.edit_id.setObjectName("edit_id")
        self.gridLayout_5.addWidget(self.edit_id, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_edit_inv)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 75 14pt \"Century Gothic\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 2, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem19, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_edit_inv, "")
        self.verticalLayout.addWidget(self.tabs)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem20, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_exit = QtWidgets.QAction(MainWindow)
        self.act_exit.setObjectName("act_exit")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.menu_file.addAction(self.act_exit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.act_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parts Inventory Manager V1.0.0"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.app_label.setText(_translate("MainWindow", "Parts Inventory Manager"))
        self.label_14.setText(_translate("MainWindow", "Search for references with count levels less than or equal to:"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        item = self.table_inv.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_inv.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reference"))
        item = self.table_inv.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Part Name"))
        item = self.table_inv.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Min Area"))
        item = self.table_inv.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max Area"))
        item = self.table_inv.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "No. of Holes"))
        item = self.table_inv.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Min Diameter"))
        item = self.table_inv.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Max Diameter"))
        item = self.table_inv.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Count"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_inv_dets), _translate("MainWindow", "Inventory Details"))
        self.label.setText(_translate("MainWindow", "Number of References:"))
        self.num_ref.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Min. Number of Holes:"))
        self.min_num_holes_ref.setText(_translate("MainWindow", "REF"))
        self.min_num_holes.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Number of Part Types:"))
        self.num_parts.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Max. Number of Holes:"))
        self.max_num_holes.setText(_translate("MainWindow", "0"))
        self.max_num_holes_ref.setText(_translate("MainWindow", "REF"))
        self.label_15.setText(_translate("MainWindow", "Top 3 references with the lowest inventory levels"))
        item = self.table_top_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Reference"))
        item = self.table_top_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Part Name"))
        item = self.table_top_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Count"))
        self.btn_check.setText(_translate("MainWindow", "Check"))
        self.tabs.setTabText(self.tabs.indexOf(self.inv_stats_tab), _translate("MainWindow", "Inventory Statistics"))
        self.btn_first.setText(_translate("MainWindow", "<<"))
        self.btn_prev.setText(_translate("MainWindow", "<"))
        self.btn_next.setText(_translate("MainWindow", ">"))
        self.btn_last.setText(_translate("MainWindow", ">>"))
        self.btn_update.setText(_translate("MainWindow", "Update"))
        self.btn_del.setText(_translate("MainWindow", "Delete"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.label_12.setText(_translate("MainWindow", "Count:"))
        self.label_13.setText(_translate("MainWindow", "ID:"))
        self.label_11.setText(_translate("MainWindow", "Max. Diameter:"))
        self.label_10.setText(_translate("MainWindow", "Min. Diameter:"))
        self.label_6.setText(_translate("MainWindow", "Min. Area:"))
        self.label_9.setText(_translate("MainWindow", "Number of Holes:"))
        self.label_8.setText(_translate("MainWindow", "Max. Area:"))
        self.label_4.setText(_translate("MainWindow", "Part Name:"))
        self.label_2.setText(_translate("MainWindow", "Reference:"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_edit_inv), _translate("MainWindow", "Edit Inventory"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.act_exit.setText(_translate("MainWindow", "Exit"))
        self.act_exit.setStatusTip(_translate("MainWindow", "Click to exit the application"))
        self.act_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.about.setText(_translate("MainWindow", "About"))
# import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
